
-- STATE RECORDS

INSERT INTO state (state_name, region) VALUES 
('Alabama', 'Southeast'),
('Alaska', 'Northeast'),
('Arizona', 'Southeast'),
('Arkansas', 'Southeast'),
('California', 'West'),
('Colorado', 'West'),
('Connecticut', 'Northeast'),
('Delaware', 'Northeast'),
('Florida', 'Southeast'),
('Georgia', 'Southeast'),
('Hawaii', 'West'),
('Idaho', 'West'),
('Illinois', 'Northeast'),
('Indiana', 'Midwest'),
('Iowa', 'Midwest'),
('Kansas', 'Midwest'),
('Kentucky', 'Southeast'),
('Louisiana', 'Southeast'),
('Maine', 'Northeast'),
('Maryland', 'Northeast'),
('Massachusetts', 'Northeast'),
('Michigan', 'Northeast'),
('Minnesota', 'West'),
('Mississippi', 'Southeast'),
('Missouri', 'Midwest'),
('Montana', 'West'),
('Nebraska', 'Midwest'),
('Nevada', 'West'),
('New Hampshire', 'Northeast'),
('New Jersey', 'Northeast'),
('New Mexico', 'Southwest'),
('New York', 'Northeast'),
('North Carolina', 'Southeast'),
('North Dakota', 'Midwest'),
('Ohio', 'Northeast'),
('Oklahoma', 'Southeast'),
('Oregon', 'West'),
('Pennsylvania', 'Northeast'),
('Rhode Island', 'Northeast'),
('South Carolina', 'Southeast'),
('South Dakota', 'Midwest'),
('Tennessee', 'Southeast'),
('Texas', 'Southeast'),
('Utah', 'West'),
('Vermont', 'Northeast'),
('Virginia', 'Southeast'),
('Washington', 'Northwest'),
('West Virginia', 'Southeast'),
('Wisconsin', 'Northeast'),
('Wyoming', 'West');